version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule: { interval: weekly, day: monday, time: '08:30', timezone: 'Asia/Seoul' }
    open-pull-requests-limit: 8
    rebase-strategy: auto
    labels: ['dependencies', 'automated']
    groups:
      eslint-and-tools:
        { patterns: ['eslint*', '@typescript-eslint/*', 'prettier', 'eslint-*', 'lint-*'] }
      types-packages: { patterns: ['@types/*'] }
      tooling: { patterns: ['vite*', 'webpack*', 'rollup*', 'ts-node', 'ts-jest'] }
      runtime: { patterns: ['typescript', 'cross-env', 'dotenv'] }
